// Copyright (c) 2012-2016 Eli Janssen
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

package tai64n

import "time"

// http://maia.usno.navy.mil/ser7/tai-utc.dat
// http://www.stjarnhimlen.se/comp/time.html
var tia64nDifferences = []struct {
	t      time.Time
	offset int64
}{
	{time.Date(1972, 1, 1, 0, 0, 0, 0, time.UTC), 10},
	{time.Date(1972, 1, 7, 0, 0, 0, 0, time.UTC), 11},
	{time.Date(1973, 1, 1, 0, 0, 0, 0, time.UTC), 12},
	{time.Date(1974, 1, 1, 0, 0, 0, 0, time.UTC), 13},
	{time.Date(1975, 1, 1, 0, 0, 0, 0, time.UTC), 14},
	{time.Date(1976, 1, 1, 0, 0, 0, 0, time.UTC), 15},
	{time.Date(1977, 1, 1, 0, 0, 0, 0, time.UTC), 16},
	{time.Date(1978, 1, 1, 0, 0, 0, 0, time.UTC), 17},
	{time.Date(1979, 1, 1, 0, 0, 0, 0, time.UTC), 18},
	{time.Date(1980, 1, 1, 0, 0, 0, 0, time.UTC), 19},
	{time.Date(1981, 1, 7, 0, 0, 0, 0, time.UTC), 20},
	{time.Date(1982, 1, 7, 0, 0, 0, 0, time.UTC), 21},
	{time.Date(1983, 1, 7, 0, 0, 0, 0, time.UTC), 22},
	{time.Date(1985, 1, 7, 0, 0, 0, 0, time.UTC), 23},
	{time.Date(1988, 1, 1, 0, 0, 0, 0, time.UTC), 24},
	{time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC), 25},
	{time.Date(1991, 1, 1, 0, 0, 0, 0, time.UTC), 26},
	{time.Date(1992, 1, 7, 0, 0, 0, 0, time.UTC), 27},
	{time.Date(1993, 1, 7, 0, 0, 0, 0, time.UTC), 28},
	{time.Date(1994, 1, 7, 0, 0, 0, 0, time.UTC), 29},
	{time.Date(1996, 1, 1, 0, 0, 0, 0, time.UTC), 30},
	{time.Date(1997, 1, 7, 0, 0, 0, 0, time.UTC), 31},
	{time.Date(1999, 1, 1, 0, 0, 0, 0, time.UTC), 32},
	{time.Date(2006, 1, 1, 0, 0, 0, 0, time.UTC), 33},
	{time.Date(2009, 1, 1, 0, 0, 0, 0, time.UTC), 34},
	{time.Date(2012, 1, 7, 0, 0, 0, 0, time.UTC), 35},
	{time.Date(2015, 1, 7, 0, 0, 0, 0, time.UTC), 36},
}

var tia64nSize = len(tia64nDifferences)
